services:
  backend:
    build: .
    env_file:
      - .env
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn chathf.wsgi:application --bind 0.0.0.0:8000  --workers 3 --timeout 180"
    volumes:
      - .:/app
      - static_volume:/static
      - media_volume:/media
      - hf_cache:/app/hf_models
    depends_on:
      - db
    environment:
      DB_NAME: chathf
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASS}
      DB_HOST: db
      DB_PORT: 5432

      # Hugging Face
      HF_HOME: /app/hf_models
      HUGGINGFACE_HUB_TOKEN: ${HF_TOKEN}

  db:
    image: postgres:15
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_DB: chathf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASS}
    ports:
      - "8080:80"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - media_volume:/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
  hf_cache: